#!/usr/bin/env python3.8
from bs4 import BeautifulSoup as bs
import sys

speaker = sys.argv[2]
f = sys.argv[1]
with open(f) as fp:
    soup = bs(fp, 'lxml')
    speeches = soup.findAll("speech", {"by": '#' + speaker})
    print(len(speeches))
